### ISSUE TITLE
Please provide the training dataset and training code

### ISSUE THREAD

**Issue by DragonM096** [sohailahmedkhan/CLIPping-the-Deception#1]
Hello dear author, may I ask if you can provide your training dataset and code? Thank you.

**Comment by sohailahmedkhan** [comment]
Hi. We use same training data as [this](https://arxiv.org/abs/2302.10174) and [this](https://github.com/PeterWang512/CNNDetection/tree/master) study. 

You can download training dataset from this [link](https://drive.google.com/file/d/1iVNBV0glknyTYGA9bCxT_d0CVTOgGcKh/view?usp=sharing).

We will soon upload the training code. For now, you can find the evaluation code in our repository.
